kind: Template
apiVersion: v1
metadata:
  name: che-starter
  creationTimestamp: null
objects:
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: che-starter
    creationTimestamp: null
    generation: 1
    labels:
      app: che-starter
  spec:
    strategy:
      type: Rolling
      rollingParams:
        updatePeriodSeconds: 1
        intervalSeconds: 1
        timeoutSeconds: 600
        maxUnavailable: 25%
        maxSurge: 25%
      resources: {}
    triggers:
      - type: ConfigChange
    replicas: 1
    test: false
    selector:
      app: che-starter
      deploymentconfig: che-starter
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: che-starter
          deploymentconfig: che-starter
      spec:
        volumes:
          - name: che-starter-volume-1
            emptyDir: {}
        containers:
          - env:
            - name: GITHUB_TOKEN_URL
              valueFrom:
                configMapKeyRef:
                  name: che-starter
                  key: github.tokenurl
            - name: OPENSHIFT_TOKEN_URL
              valueFrom:
                configMapKeyRef:
                  name: che-starter
                  key: oso.tokenurl
            - name: OSO_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: che-starter
                  key: oso.address
            - name: OSO_DOMAIN_NAME
              valueFrom:
                configMapKeyRef:
                  name: che-starter
                  key: oso.domain.name
            - name: KUBERNETES_CERTS_CA_FILE
              valueFrom:
                configMapKeyRef:
                  name: che-starter
                  key: kubes.certs.ca.file
            name: che-starter
            image: ${IMAGE}:${IMAGE_TAG}
            livenessProbe:
              failureThreshold: 3
              httpGet:
                path: /status
                port: 8080
                scheme: HTTP
              initialDelaySeconds: 120
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 1
            readinessProbe:
              failureThreshold: 3
              httpGet:
                path: /status
                port: 8080
                scheme: HTTP
              initialDelaySeconds: 60
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 1
            ports:
              - containerPort: 10000
                protocol: TCP
            terminationMessagePath: /dev/termination-log
            resources:
              requests:
                cpu: 50m
                memory: 1Gi
              limits:
                cpu: 500m
                memory: 2Gi
            volumeMounts:
              - name: che-starter-volume-1
                mountPath: /tmp
            imagePullPolicy: IfNotPresent
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
        securityContext: {}
  status: {}
- kind: Service
  apiVersion: v1
  metadata:
    name: che-starter
    creationTimestamp: null
    labels:
      app: che-starter
  spec:
    ports:
      - name: 10000-tcp
        protocol: TCP
        port: 10000
        targetPort: 10000
    selector:
      app: che-starter
      deploymentconfig: che-starter
    type: ClusterIP
    sessionAffinity: None
  status:
    loadBalancer: {  }
- kind: Route
  apiVersion: v1
  metadata:
    name: che-starter
    creationTimestamp: null
  spec:
    host: che-starter.$(minishift ip).nip.io
    to:
      kind: Service
      name: che-starter
      weight: 100
    wildcardPolicy: None
parameters:
- name: IMAGE
  value: rhche/che-starter
- name: IMAGE_TAG
  value: latest
